trigger:
- master

variables:
  awsServiceConnection: 'Images administrator (ECR/ECS)'
  region: 'us-east-1'
  repositoryName: 'arquisoft-proyecto1-mainapp-container'
  clusterName: 'arquisoft-proyecto1-mainapp-cluster'
  serviceName: 'arquisoft-proyecto1-mainapp-task-service'

pool:
  name: 'Default' # Tu máquina personal

jobs:
- job: BuildAndDeploy
  steps:
  # PASO 1: Construir la imagen localmente (Docker nativo)
  - script: |
      docker build -t $(repositoryName):latest .
    displayName: 'Docker Build'

  # PASO 2: Push a ECR (Siguiendo la documentación oficial)
  - task: ECRPushImage@1
    displayName: 'Push Image to Amazon ECR'
    inputs:
      awsCredentials: $(awsServiceConnection)
      regionName: 'us-east-1'
      imageSource: 'imagename' # Único valor válido según la doc
      sourceImageName: $(repositoryName)
      sourceImageTag: 'latest'
      repositoryName: $(repositoryName)
      pushTag: 'latest' # El tag que quedará en AWS

  # PASO 3: Actualizar Fargate
  - task: AWSCLI@1
    displayName: 'Update Fargate Service'
    inputs:
      awsCredentials: $(awsServiceConnection)
      regionName: 'us-east-1'
      awsCommand: 'ecs'
      awsSubcommand: 'update-service'
      awsArguments: '--cluster $(clusterName) --service $(serviceName) --force-new-deployment'