# Generated by Django 5.2.12 on 2026-04-03 20:25

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('duracion', models.DurationField(help_text='Duración del proceso de análisis.')),
            ],
            options={
                'verbose_name': 'Análisis',
                'verbose_name_plural': 'Análisis',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_empresa', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=255)),
                ('rol', models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('coo', 'COO'), ('po', 'PO'), ('equipo_tecnico', 'Equipo Técnico'), ('operacion_y_soporte', 'Operación y Soporte')], default='equipo_tecnico', max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('duracion', models.DurationField(help_text='Duración de la sesión o del evento de acceso.')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Metricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='core.analisis')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_notificacion', models.DateTimeField()),
                ('asunto', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_notificacion'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('aws', 'AWS'), ('gcp', 'GCP')], max_length=16)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_cloud', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Proveedor cloud',
                'verbose_name_plural': 'Proveedores cloud',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='core.area')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='RecursoCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('computo', 'Cómputo'), ('almacenamiento', 'Almacenamiento'), ('base_de_datos', 'Base de datos'), ('red', 'Red'), ('seguridad', 'Seguridad'), ('monitorio', 'Monitorio')], max_length=32)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('detenido', 'Detenido'), ('cancelado', 'Cancelado'), ('suspendido', 'Suspendido')], default='activo', max_length=16)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='core.proveedorcloud')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Recurso cloud',
                'verbose_name_plural': 'Recursos cloud',
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=512)),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='core.metricas')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='core.recursocloud')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('id_transaccion', models.BigIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=16)),
                ('notificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='core.notificacion')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.AddField(
            model_name='analisis',
            name='reporte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='core.reporte'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.reporte'),
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=14)),
                ('divisa', models.CharField(choices=[('usd', 'USD'), ('cop', 'COP')], max_length=8)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='core.area')),
                ('consumo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costo', to='core.consumo')),
            ],
            options={
                'verbose_name': 'Costo',
                'verbose_name_plural': 'Costos',
                'indexes': [models.Index(fields=['area'], name='core_costo_area_id_cb334d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='proveedorcloud',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uniq_proveedor_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='recursocloud',
            index=models.Index(fields=['proyecto', 'estado'], name='core_recurs_proyect_b4c659_idx'),
        ),
        migrations.AddIndex(
            model_name='recursocloud',
            index=models.Index(fields=['proveedor', 'tipo'], name='core_recurs_proveed_73b258_idx'),
        ),
        migrations.AddIndex(
            model_name='consumo',
            index=models.Index(fields=['recurso'], name='core_consum_recurso_0948e0_idx'),
        ),
    ]
