# Generated by Django 5.2.12 on 2026-04-03 20:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='acceso',
            name='exitoso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='acceso',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceso',
            name='ruta',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='acceso',
            name='tipo_evento',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('api', 'API / recurso'), ('otro', 'Otro')], default='login', max_length=16),
        ),
        migrations.AddField(
            model_name='usuario',
            name='area_alcance',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para responsable de área (y opcional según política).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_con_alcance', to='core.area'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa cliente a la que pertenece el usuario (vacío para personal BITE).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='proyecto_alcance',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para responsable de proyecto o colaborador limitado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_con_alcance', to='core.proyecto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_cliente',
            field=models.CharField(blank=True, choices=[('ejecutivo_empresa', 'Ejecutivo / vista empresa'), ('responsable_area', 'Responsable de área'), ('responsable_proyecto', 'Responsable de proyecto'), ('colaborador_limitado', 'Colaborador (alcance restringido)')], help_text='Solo usuarios cliente: qué tan amplio es su vista (empresa, área o proyecto).', max_length=32),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Duración de la sesión o del evento de acceso.'),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Nulo si el intento no identifica a un usuario (p. ej. credencial inválida).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SolicitudReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(choices=[('empresa', 'Empresa'), ('area', 'Área'), ('proyecto', 'Proyecto')], max_length=16)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('periodo_parcial', models.BooleanField(default=False, help_text='True si el mes aún está en curso y los montos son acumulados a la fecha.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_cola', 'En cola'), ('completado', 'Completado'), ('rechazado_sobrecarga', 'Rechazado por sobrecarga'), ('error', 'Error')], default='pendiente', max_length=32)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('divisa', models.CharField(choices=[('usd', 'USD'), ('cop', 'COP')], default='usd', max_length=8)),
                ('desglose', models.JSONField(blank=True, help_text='Detalle opcional (por servicio, proveedor, etc.) para tableros o exportación.', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reporte', to='core.area')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reporte', to='core.empresa')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reporte', to='core.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de reporte mensual',
                'verbose_name_plural': 'Solicitudes de reporte mensual',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['empresa', 'anio', 'mes'], name='core_solici_empresa_904a80_idx')],
            },
        ),
    ]
