# Generated by Django 5.2.12 on 2026-04-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requisitos_cliente_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='costo',
            name='fecha',
            field=models.DateField(blank=True, help_text='Fecha de imputación del costo (p. ej. cierre diario/mensual del proveedor).', null=True),
        ),
    ]
