# Generated by Django 5.2.12 on 2026-04-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_costo_fecha_reportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursocloud',
            name='cpu_utilizacion_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Última utilización de CPU observada (0–100). Para análisis FinOps / recursos infrautilizados.', max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='recursocloud',
            index=models.Index(fields=['estado', 'cpu_utilizacion_pct'], name='core_recurs_estado_eca720_idx'),
        ),
    ]
